# -*- coding: utf-8 -*-
"""nlp project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fD5LZgFKNaz1if70-Rxn1I1KaXB9Q1R7
"""

!pip install transformers sentencepiece

from transformers import MarianMTModel, MarianTokenizer
model_name = "Helsinki-NLP/opus-mt-en-es"

# Load tokenizer and model
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

def translate_en_to_es(text_list):
    """
    Translates a list of English sentences into Spanish.
    """
    # Tokenize and prepare for the model
    inputs = tokenizer(text_list, return_tensors="pt", padding=True, truncation=True)

    # Generate translated text
    translated_tokens = model.generate(**inputs)

    # Decode into Spanish sentences
    translations = [tokenizer.decode(t, skip_special_tokens=True) for t in translated_tokens]
    return translations
# Example English sentences
english_sentences = [
    "Hello, how are you?",
    "I love learning new languages.",
    "This is a translation example.",
    "The weather is beautiful today.",
    "Artificial Intelligence is transforming the world."
]

# Translate to Spanish
spanish_translations = translate_en_to_es(english_sentences)

# Print results
for en, es in zip(english_sentences, spanish_translations):
    print(f"EN: {en}\nES: {es}\n")